name: Cimon by Cycode
description: Runtime Security Solution for your CI/CD Pipeline
branding:
  icon: shield
  color: green
author: CycodeLabs
inputs:
  client-id:
    description: Cimon client ID for authentication
    required: false
  secret:
    description: Cimon secret for authentication
    required: false
  url:
    description: Cimon endpoint for authentication
    required: false
  release-path:
    description: Path to Cimon release file (Used for debugging)
    required: false
    default: ''
  subjects:
    description: A white space seperated list of paths, or base64-encoded subjects. Each path can be file, directory or image reference
    required: false
    default: ''
  image-ref:
    description: (deprecated) The container reference to generate provenance for. Either subjects or imageRef are required
    required: false
    default: ''
  sign-key:
    description: Input path to a private ECDSA/RSA/ED25519 key used to sign provenance statement
    required: false
    default: ''
  keyless:
    description: Allow keyless signature if no signing key is provided
    required: false
    default: 'false'
  allow-tlog:
    description: Allow the creation of a Rekor transparency log (TLog) entry.
    required: false
    default: 'true'
  allow-timestamp:
    description: Allow timestamping of the artifact signature against a timestamping authority.
    required: false
    default: 'false'
  fulcio-server-url:
    description: Fulcio server URL
    required: false
    default: 'https://fulcio.sigstore.dev'
  rekor-server-url:
    description: Rekor server URL
    required: false
    default: 'https://rekor.sigstore.dev'
  timestamp-server-url:
    description: Timestamp server URL
    required: false
  provenance-output:
    description: Provenance output path. Can be absolute path, or relative path to the default working directory
    required: false
    default: 'provenance.intoto.jsonl'
  signed-provenance-output:
    description: Signed provenance output path. Can be absolute path, or relative path to the default working directory
    required: false
    default: 'provenance.intoto.jsonl.sig'
  github-token:
    description: GitHub token for enriching build information
    required: false
    default: ${{ github.token }}
  report-job-summary:
    description: Enable to report the provenance documents as job summary output
    required: false
    default: 'true'
  report-artifact:
    description: Enable to report the provenance documents as job artifacts
    required: false
    default: 'true'
  log-level:
    description: Log level (Used for debugging)
    required: false
    default: 'info'
  fail-on-error:
    description: Fail the CI if Cimon encountered an error
    required: false
    default: 'false'

runs:
  using: node20
  main: 'dist/index.js'
