name: Cimon by Cycode
description: Runtime Security Solution for your CI/CD Pipeline
branding:
  icon: shield
  color: green
author: CycodeLabs
inputs:
  client-id:
    description: Cimon client ID for authentication
    required: false
  secret:
    description: Cimon secret for authentication
    required: false
  url:
    description: Cimon endpoint for authentication
    required: false
  release-path:
    description: Path to Cimon release file (Used for debugging)
    required: false
    default: ""
  subjects:
    description: A white space seperated list of paths, or base64-encoded subjects. Either subjects or imageRef are required
    required: true
  image-ref:
    description: The container reference to generate provenance for. Either subjects or imageRef are required
    required: false
    default: ""
  sign-key:
    description: Input path to a private ECDSA/RSA/ED25519 key used to sign provenance statement
    required: false
    default: ""
  provenance-output:
    description: Provenance output path. Can be absolute path, or relative path to the default working directory
    required: false
    default: "provenance.intoto.jsonl"
  signed-provenance-output:
    description: Signed provenance output path. Can be absolute path, or relative path to the default working directory
    required: false
    default: "provenance.intoto.jsonl.sig"
  github-context:
    description: Information about the workflow run
    required: false
    default: ""
  report-job-summary:
    description: Enable to report the provenance documents as job summary output
    required: false
    default: "true"
  report-artifact:
    description: Enable to report the provenance documents as job artifacts
    required: false
    default: "true"
  log-level:
    description: Log level (Used for debugging)
    required: false
    default: "info"
  fail-on-error:
    description: Fail the CI if Cimon encountered an error
    required: false
    default: "false"

runs:
  using: node16
  main: "dist/index.js"