name: Cimon by Cycode
description: Runtime Security Solution for your CI/CD Pipeline
branding:
  icon: shield
  color: green
author: CycodeLabs
inputs:
  client-id:
    description: Cimon client ID for authentication
    required: false
  secret:
    description: Cimon secret for authentication
    required: false
  url:
    description: Cimon endpoint for authentication
    required: false
  prevent:
    description: Enable prevention mode
    required: true
    default: 'false'
  allowed-ips:
    description: A comma-separated list of allowed IP addresses
    required: false
  allowed-hosts:
    description: A comma-separated list of domain names
    required: false
  ignored-ip-nets:
    description: |
      A comma or white space separated list of ignored IP networks in CIDR
      notation, e.g. 10.0.0.0/8, 172.16.0.0/12. This setting is mandatory if
      your workflow runs containers attached to a custom network with
      configured sub-range. In other words, inter-container networking is
      usually ignored by Cimon. Cimon implicitly ignores 10.0.0.0/8 and
      172.16.0.0/12 networks.
    required: false
  github-token:
    description: GitHub token for enriching build information
    required: false
    default: ${{ github.token }}
  report-job-summary:
    description: Report results through job summary output
    required: false
    default: 'true'
  report-process-tree:
    description: Enable to report the process tree
    required: false
    default: 'false'
  slack-webhook-endpoint:
    description: Slack webhook endpoint to report security events
    required: false
  apply-fs-events:
    description: Enable processing filesystem events and display them in the process tree report
    required: false
    default: 'false'
  log-level:
    description: Log level (Used for debugging)
    required: false
    default: 'info'
  feature-gates:
    description: Set of key=value pairs that describe Cimon features.
    required: false
  fail-on-error:
    description: Fail the CI if Cimon encountered an error
    required: false
    default: 'false'
  release-path:
    description: Path to Cimon release file (Used for debugging)
    required: false
    default: ''

runs:
  using: node16
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
